# Generated by Django 3.2.16 on 2022-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/df4j1glpo/image/upload/v1668434573/samples/default_profile_m2uned.jpg', upload_to='images/'),
        ),
    ]
